spring:
  application:
    name: "biometric-auth"
  datasource:
    url: jdbc:postgresql://localhost:5432/biometric
    username: postgres
    password: 110371
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: false
        format-sql: true
        use_sql_comments: true
        generate_statistics: false
        jdbc:
          time_zone: "Europe/Moscow"
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true

application:
  registration-iterations: "5"
  password: "Hello world goodbye all"
  threshold: "0.5"